services:
  - type: worker
    name: tg-bot-me
    env: python
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.8
    buildCommand: pip install -r requirements.txt
    startCommand: python -m bot.main
    autoDeploy: true
